### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by agraf**
While compiling with gcc on a Linux system, I stumbled over a few obscure build failures. With these 2 commits, OcSupportPkg builds just fine though.

### CODE REVIEW

**Comment by vit9696** [comment]
Hello,

These issues indeed seem strange.

* CharToUpper issue is most likely caused by our migration to EDK II stable, as Intel obsoleted and dropped UDK support and security maintenance. The information can be found here https://github.com/acidanthera/bugtracker/issues/323. While it is still work in progress, soon there will be more EDK II-only dependencies, and supporting UDK is unfortunately out of our scope. Currently we have the latest tag checked out in https://github.com/acidanthera/audk, but you may freely use original version.
* MIN_INT64 must be defined in MdePkg/Include/Base.h, and this file must be included automatically in every compilation unit. https://github.com/acidanthera/audk does seem to be fine with it. Perhaps the issue is somewhere else?

The fact that these issues arised makes me feel that we need CI support with other compilers, potentially reanimating our https://github.com/acidanthera/ocbuild project.

Vit

**Comment by agraf** [comment]
Yes, I was quite puzzled by them too. My UDK2018 Base.h for example did not contain any MIN_ defines. It only got introduced in https://github.com/tianocore/edk2/commit/d7a09cb86a0416c099fa3a9e0fbe2c8f399b28de so it's not part of a UDK yet:

>$ git tag --contains d7a09cb86a0416c099fa3a9e0fbe2c8f399b28de
>edk2-stable201808
>edk2-stable201811
>edk2-stable201903
>edk2-stable201905

As for CharToUpper(), I suppose the problem is similar. So really this pull request only fixes build with older edk2 version. Feel free to reject it, I mostly wanted to document what was necessary to make things build :).

**Comment by vit9696** [comment]
Right, hm. Well, point is:

- why do you use UDK 2018 (Intel will not make UDK 2019 or anything alike, project is closed)?
- do you plan to switch to edk2 stable?
- is there any reason to support UDK 2018 at least partially?

Depending on the answers we can make some considerations I believe.

**Comment by agraf** [comment]
I mostly used it because it was the most obvious stable base to go from. I understand that there are the stable tags now, but I did not realize that when I started :). Also, I locally can always just carry patches to make bits work, so don't worry too much about me particularly.

The bigger question really is whether support for UDK2018 is desired. I am not sure there. I guess if there's a conscious decision not to, that's fine by me as well.

**Comment by vit9696** [comment]
Right, in this case I believe there is not much reason for us to merge it. In future there will be more difficulties to support dating UDK, and we do not have the resources for the burden. Closing =)

**Pull request closed without merging**
